
    "import re  # On importe le module regex\n",
    "\n",
    "\n",
    "def lire_journaux(nom_fichier):\n",
    "    \"\"\"Lit un fichier de journaux et retourne une liste de dictionnaires.\"\"\"\n",
    "    journaux = []  # Liste vide où l'on va stocker les journaux analysés\n",
    "    \n",
    "    with open(nom_fichier, 'r') as fichier:\n",
    "        for ligne in fichier:  # On lit le fichier ligne par ligne\n",
    "            # Expression régulière pour extraire les informations\n",
    "            match = re.match(r\"\\[(.*?)\\] (\\w+) : (.+)\", ligne.strip())\n",
    "            if match:\n",
    "                heure, utilisateur, activite = match.groups()  # On extrait les 3 éléments\n",
    "                journaux.append({\n",
    "                    \"heure\": heure,               # clé \"heure\" reçoit la valeur extraite\n",
    "                    \"utilisateur\": utilisateur,   # clé \"utilisateur\" reçoit la valeur extraite\n",
    "                    \"activité\": activite          # clé \"activité\" reçoit la valeur extraite\n",
    "                })\n",
    "    \n",
    "    return journaux\n",
    "\n",
    "\n",
    "nom_fichier = \"journaux.txt\"  # On définit le nom du fichier\n",
    "\n",
    "with open(nom_fichier, 'w') as f:\n",
    "    f.write(\"[08:00] user1 : Login\\n\")\n",
    "    f.write(\"[08:05] user1 : Open Application\\n\")\n",
    "    f.write(\"[08:10] user2 : Login\\n\")\n",
    "    f.write(\"[08:15] user1 : Logout\\n\")\n",
    "\n",
    "\n",
    "logs = lire_journaux(nom_fichier)\n",
    "print(\" Journaux analysés :\", logs)\n",
    "\n",
    "\n",
    "def compter_activites(journaux):\n",
    "    \"\"\"Compte le nombre d'activités par utilisateur.\"\"\"\n",
    "    activites_par_utilisateur = {}  # Dictionnaire pour stocker le comptage\n",
    "\n",
    "    for entree in journaux:  # Parcourt chaque entrée du journal\n",
    "        utilisateur = entree[\"utilisateur\"]  # Récupère le nom de l'utilisateur\n",
    "        if utilisateur in activites_par_utilisateur:\n",
    "            activites_par_utilisateur[utilisateur] += 1  # Incrémente le compteur\n",
    "        else:\n",
    "            activites_par_utilisateur[utilisateur] = 1  # Initialise à 1\n",
    "\n",
    "    return activites_par_utilisateur  # Retourne le dictionnaire\n",
    "\n",
    "\n",
    "resultat = compter_activites(logs)\n",
    "print(\" Nombre d'activités par utilisateur :\", resultat)\n",
    "\n",
    "def filtrer_activites(journaux, utilisateur):\n",
    "    \"\"\"Générateur qui retourne uniquement les activités d'un utilisateur donné.\"\"\"\n",
    "    for journal in journaux:\n",
    "        if journal[\"utilisateur\"] == utilisateur:\n",
    "            yield journal  # Génère les journaux de cet utilisateur\n",
    "# Filtrer uniquement les activités de \"user1\"\n",
    "activites_user1 = filtrer_activites(logs, \"user1\")\n",
    "\n",
    "\n",
    "for activite in activites_user1:\n",
    "    print(\"activités spécifiques:\",activite)\n",
    "\n",
    "def heures_actives(journaux):\n",
    "    \"\"\"Retourne une liste des heures uniques où des activités ont été enregistrées.\"\"\"\n",
    "    heures = set()  # Utilisation d'un ensemble pour éviter les doublons\n",
    "    \n",
    "    for journal in journaux:\n",
    "        heures.add(journal[\"heure\"])  # Ajoute l'heure à l'ensemble\n",
    "    \n",
    "    return sorted(heures)\n",
    "heures_uniques = heures_actives(logs)\n",
    "\n",
    "# Afficher le résultat\n",
    "print(heures_uniques)\n",
    "\n",
    "def sauvegarder_resume(nom_fichier, resume):\n",
    "    \"\"\"Sauvegarde un résumé sous forme de dictionnaire dans un fichier texte.\"\"\"\n",
    "    with open(nom_fichier, 'w') as fichier:\n",
    "        for utilisateur, nb_activites in resume.items():\n",
    "            fichier.write(f\"{utilisateur} : {nb_activites}\\n\")  \n",
    "            \n",
    "resume_activites = compter_activites(logs)\n",
    "\n",
    "sauvegarder_resume(\"resume.txt\", resume_activites)\n",
    "\n",
    "\n",
    "print(\"Résumé des activités sauvegardé dans 'resume.txt'.\")"
  

 
